### ISSUE TITLE
Formulas in pythonhosted.org don't display properly

### ISSUE THREAD

**Issue by JaviMerino** [ARM-software/bart#25]
Documentation created with `make -C docs/api_reference html` displays the formula in the documentation using mathjax.  However, the formulas don't display properly when uploaded to pythonhosted.org: https://pythonhosted.org/bart-py/bart.sched.SchedAssert.html#bart.sched.SchedAssert.SchedAssert.getDutyCycle

**Comment by sinkap** [comment]
It is again HTTP vs HTTPS. The mathjax include that is generated by sphynx is http while we are opening the doc in HTTPS. We will need to correct some templates/generation code for this.

**Comment by JaviMerino** [comment]
I'll close it when we upload the new version of bart and we verify it properly.

**Comment by JaviMerino** [comment]
Formulas now display correctly :blush:
