### ISSUE TITLE
PIP install failing due to missing README.rst

### ISSUE THREAD

**Issue by Sticklyman1936** [ARM-software/bart#56]
I am unable to install BART via pip as it tries using 'README.rst' which does not exist. The error I see is the following:

`Collecting BART
  Downloading bart-0.0.3.tar.gz (266kB)
    100% |################################| 276kB 2.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qBr2fA/BART/setup.py", line 61, in <module>
        long_description=open("README.rst").read(),
    IOError: [Errno 2] No such file or directory: 'README.rst'
`

**Comment by mdigiorgio** [comment]
You are installing the wrong `bart`. The command you should use is:

``` bash
$ sudo pip install bart-py
```

The `-py` suffix in the package name solves your issue.

**Comment by Sticklyman1936** [comment]
Ah, sorry! I'd forgotten about that part. Please excuse the noise!
